In [1]:
# Imports
import qutip as qt
import matplotlib.pyplot as plt  # not used this time, but we'll want it later
import numpy as np

from scipy.optimize import curve_fit # not used this time, but we'll want it later


Hello Qutip World

In [2]:
print("Qutip version:",qt.__version__) # Should be on 5.X.X

Qutip version: 5.2.2


In [3]:
'''
This code is simply instantiating and using a couple of basic tools in QuTiP, if it runs without error you should be all set.
'''

zero_state = qt.basis(2,0)
plus_state = (qt.basis(2,0) + qt.basis(2,1)).unit()

print(f"<0|+> = {zero_state.overlap(plus_state)}")
print(f"|<0|+>|^2 = {np.abs(zero_state.overlap(plus_state))**2}")

print(f"<0|X|0> = {qt.expect(qt.sigmax(),zero_state)}")
print(f"<+|X|+> = {qt.expect(qt.sigmax(),plus_state)}")

print("\nX acting on |0>:")
print(f"X|0> = {qt.sigmax()*zero_state}")

oscillator_trunc = 5
a = qt.destroy(oscillator_trunc)
a_dag = a.dag()

print("\nLet's try to compute [a,adag]:")
commutator = a* a_dag - a_dag * a
print(commutator)
print("This should be the identity operator, but we see that with finite truncation of our Hilbert space, we can get get artifacts.")


print("\nAll done!")


<0|+> = (0.7071067811865475+0j)
|<0|+>|^2 = 0.4999999999999999
<0|X|0> = 0.0
<+|X|+> = 0.9999999999999998

X acting on |0>:
X|0> = Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]

Let's try to compute [a,adag]:
Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]
This should be the identity operator, but we see that with finite truncation of our Hilbert space, we can get get artifacts.

All done!
